name: Build theme

on:
  push:
    paths:
      - 'src/**/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          npm i --production
          npm run build:all

      - name: Commit & push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/*.css -f
          git commit -m "Build"
          git push
