name: Build theme

on:
  push:
    paths:
      - 'src/**/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: |
          pnpm i --production
          pnpm run build:all

      - name: Commit & push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if (git status | grep -q 'up to date'); then
            echo "No changes made."
            exit 0
          else
            git add dist/*.css -f
            git commit -m "Build"
            git push
          fi
