name: Bump version and build

on:
  # Runs workflow when source changed
  push:
    paths:
      - 'src/**/*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check and bump version
        run: |
          git log -1 --name-only > /tmp/gitlog.txt
          if ! (grep -q 'package.json' /tmp/gitlog.txt && \
                grep -q 'manifest.json' /tmp/gitlog.txt); then
            npm i --production
            npm run bump:patch
          fi

      - name: Commit & push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          if (grep -q 'package.json' /tmp/gitlog.txt && \
              grep -q 'manifest.json' /tmp/gitlog.txt); then
            git add *
            git commit -m "Bump version"
            git push
          else
            echo "Already bumped."
            exit 0
          fi

  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          npm i --production
          npm run build:all

      - name: Commit & push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/*.css -f
          git commit -m "Build"
          git push
