name: Bump version and build

on:
  # Runs workflow when source changed
  push:
    paths:
      - 'src/**/*'

jobs:
  Bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check and bump version
        run: |
          npm i --production
          npm run bump:patch

      - name: Commit & push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *
          git commit -m "Bump version"
          git push

  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          npm i --production
          npm run build:all

      - name: Commit & push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/*.css -f
          git commit -m "Build"
          git push
